name: GitHub Pages action
uses: peaceiris/actions-gh-pages@v3.7.3
on:
  push:
    branches:
      - main
with:
  github_token: ${{ secrets.GITHUB_TOKEN }}
  publish_dir: .
  publish_branch: master
    
